apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.15.3
    helm:
      releaseName: cert-manager
      parameters:
      - name: "crds.enabled"
        value: "true"
      - name: "prometheus.enabled"
        value: "true"
      - name: "ingressShim.defaultIssuerName"
        value: cloudflare-issuer
      - name: "ingressShim.defaultIssuerKind"
        value: ClusterIssuer
  destination:
    server: https://kubernetes.default.svc
    # name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
