apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fruit-tls-certificate
  namespace: default
spec:
  secretName: fruit-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod #cloudflare-issuer
  commonName: fruit.example.com
  dnsNames:
  - fruit.example.com
